"""Update operators table with all fields

Revision ID: 53843099d7bc
Revises: 48e1b619c90c
Create Date: 2026-01-27 22:33:39.365639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53843099d7bc'
down_revision: Union[str, Sequence[str], None] = '48e1b619c90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'operators', ['id'])
    op.create_unique_constraint(None, 'results', ['id'])
    op.create_unique_constraint(None, 'tasks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'results', type_='unique')
    op.drop_constraint(None, 'operators', type_='unique')
    # ### end Alembic commands ###
