"""Create agents table

Revision ID: 7784ca701c1d
Revises: 
Create Date: 2026-01-21 21:04:42.467363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7784ca701c1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('internal_ip', sa.String(length=45), nullable=True),
    sa.Column('external_ip', sa.String(length=45), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('architecture', sa.String(length=20), nullable=True),
    sa.Column('process_name', sa.String(length=255), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('privilege_level', sa.String(length=20), nullable=True),
    sa.Column('sleep_interval', sa.Integer(), nullable=True),
    sa.Column('jitter', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DEAD', name='agentstatus'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('listener_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
